function OutputAPInfo(filename, APinfo, APinfo2, mode,model_ID)

file = fopen(filename, mode);

temp = '';
if nargin == 4
    temp = '';
elseif nargin == 5
    temp = model_ID;
end

fprintf(file, '%i ', temp);


fprintf(file, '%f %f %f %f %f %f %f %f %f %f %f %f %f %f ', ... 
       APinfo.dVdtmax, ...
         APinfo.APD90, ...
 APinfo.APD90_max_amp, ...
         APinfo.APD20, ...
         APinfo.APD75, ...
         APinfo.APD50, ...
         APinfo.PLT20, ...
          APinfo.Vmax, ...
          APinfo.Vmin, ...
  APinfo.dVdtmax_time, ...
           APinfo.PLT, ...
        APinfo.CA_max, ...
        APinfo.CA_min, ...
        APinfo.CA_t50);


fprintf(file, '%f %f %f %f %f %f %f %f %f %f %f %f %f %f ', ... 
       APinfo2.dVdtmax, ...
         APinfo2.APD90, ...
 APinfo2.APD90_max_amp, ...
         APinfo2.APD20, ...
         APinfo2.APD75, ...
         APinfo2.APD50, ...
         APinfo2.PLT20, ...
          APinfo2.Vmax, ...
          APinfo2.Vmin, ...
  APinfo2.dVdtmax_time, ...
           APinfo2.PLT, ...
        APinfo2.CA_max, ...
        APinfo2.CA_min, ...
        APinfo2.CA_t50);



% outputing Na info
fprintf(file, '%f %f %f %f\n', ... 
        APinfo.Na_max, ...
        APinfo.Na_min, ...
        APinfo2.Na_max, ...
        APinfo2.Na_min);



fclose(file);


end


